import type { Config } from "tailwindcss";

export default {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        surface: "#f8f9ff",
        "surface-dim": "#cbdbf5",
        "surface-bright": "#f8f9ff",
        "surface-container-lowest": "#ffffff",
        "surface-container-low": "#eff4ff",
        "surface-container": "#e5eeff",
        "surface-container-high": "#dce9ff",
        "surface-container-highest": "#d3e4fe",
        "on-surface": "#0b1c30",
        "on-surface-variant": "#43474e",
        "inverse-surface": "#213145",
        "inverse-on-surface": "#eaf1ff",
        outline: "#74777f",
        "outline-variant": "#c4c6cf",
        "surface-tint": "#455f87",
        primary: "#022448",
        "on-primary": "#ffffff",
        "primary-container": "#1e3a5f",
        "on-primary-container": "#8aa4cf",
        "inverse-primary": "#adc8f5",
        secondary: "#0b61a1",
        "on-secondary": "#ffffff",
        "secondary-container": "#7cbaff",
        "on-secondary-container": "#004a7d",
        tertiary: "#212426",
        "on-tertiary": "#ffffff",
        "tertiary-container": "#363a3c",
        "on-tertiary-container": "#a1a3a5",
        error: "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
        "primary-fixed": "#d5e3ff",
        "primary-fixed-dim": "#adc8f5",
        "on-primary-fixed": "#001c3b",
        "on-primary-fixed-variant": "#2d486d",
        "secondary-fixed": "#d1e4ff",
        "secondary-fixed-dim": "#9ecaff",
        "on-secondary-fixed": "#001d36",
        "on-secondary-fixed-variant": "#00497c",
        "tertiary-fixed": "#e0e3e5",
        "tertiary-fixed-dim": "#c4c7c9",
        "on-tertiary-fixed": "#191c1e",
        "on-tertiary-fixed-variant": "#444749",
        background: "#f8f9ff",
        "on-background": "#0b1c30",
        "surface-variant": "#d3e4fe",
        accent: "#2e75b6",
      },
      spacing: {
        unit: "8px",
        "container-max": "1280px",
        gutter: "24px",
        "section-padding": "80px",
        "stack-sm": "12px",
        "stack-md": "24px",
        "stack-lg": "48px",
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.5rem",
        md: "0.75rem",
        lg: "1rem",
        xl: "1.5rem",
      },
      fontFamily: {
        h1: ["Space Grotesk", "sans-serif"],
        h2: ["Space Grotesk", "sans-serif"],
        h3: ["Space Grotesk", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "label-caps": ["Inter", "sans-serif"],
        button: ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
} satisfies Config;
